### ISSUE TITLE
サーボへの送信のみプログラムの作成

### ISSUE THREAD

**Issue by Takehiro-Hasegawa** [open-rdc/RaspberryPi4_RS485_Communication#2]
自身がプログラムの作成に手こずってるため、こちらでサポートなど議論をしていただけると幸いです。
これから、RS485_Communication_testのフォルダ内にプログラムの更新ができればと思います。

**Comment by yasuohayashibara** [comment]
今までのループバックの動作検証のプログラムはどこにありますでしょうか？

**Comment by yasuohayashibara** [comment]
こちらにB3Mを制御するノードがあるので，これをベースに開発する．
https://github.com/citbrains/kondo_driver

**Comment by Takehiro-Hasegawa** [comment]
sttyコマンドでボーレートを確認をしているがプログラムを動かすたびにボーレートが変わり安定していません
sttyコマンドでボーレートの設定もできるので検証はしてみたが、プログラムを動かしてもエラーになり再度ボーレートを確認すると全く違うボーレートに変わってしまいます

**Comment by yasuohayashibara** [comment]
以下のブランチの通信プログラムですが，B3Mのデフォルトの1.5Mbpsで通信するようになっています．
https://github.com/open-rdc/RaspberryPi4_RS485_Communication/tree/b3m_driver

以下を変更すれば他のビットレートになると思いますが，サーボモータを1.5Mbpsに設定した方が簡単かもしれません．
https://github.com/open-rdc/RaspberryPi4_RS485_Communication/blob/165718c78fea88ed4647defec9fd94569657d9c9/b3m_driver/b3m.c#L32

**Comment by Takehiro-Hasegawa** [comment]
サーボモータのビットレート変更、b3m.cのビットレート変更の2種類の検証を行いました。
結果としてはどちらともエラーになってしまいました。

**Comment by yasuohayashibara** [comment]
ここしばらく忙しいので時間を確保するのが難しいのですが，通信できるようにハードウェアをセットして置いて頂ければ，隙間の時間でソフトウェアを試行錯誤することができます．
他のソフトウェアが強い方に協力してもらっても良いと思いますが，林原が関わったほうが良い場合はお願いします．

**Comment by Takehiro-Hasegawa** [comment]
承知しました。
自分の机に全て揃えた状態にしておきます。
ありがとうございます。

**Comment by Takehiro-Hasegawa** [comment]
@yasuohayashibara 
![IMG_1284](https://user-images.githubusercontent.com/39427883/146131975-f063e2e7-d61f-4723-8247-1850039878c9.jpg)
写真左側がB3M_Manager用の回路
写真右側が検証用の回路です。

**Comment by Takehiro-Hasegawa** [comment]
キーボードのタッチパッドはタップでのクリックができません。
ボタンでのクリックをお願いします。

**Comment by yasuohayashibara** [comment]
動きました．
内容は動画を参照して下さい．

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/ePozfcW7OKo/0.jpg)](https://youtu.be/ePozfcW7OKo)

**Comment by Takehiro-Hasegawa** [comment]
ありがとうございます。
とりあえず115200bpsで進めようと思います。

**Comment by yasuohayashibara** [comment]
解決したためissueを閉じます．
